import React from 'react';
import { Container, Title, Text, Paper, Stack, Box } from '@mantine/core';

const TermsOfService: React.FC = () => {
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return (
    <Container size="lg" py="xl">
      <Paper shadow="sm" p="xl">
        <Stack gap="xl">
          <Box ta="center">
            <Title order={1}>TERMS OF SERVICE AGREEMENT</Title>
            <Text size="lg" mt="md">Last Updated: {currentDate}</Text>
          </Box>

          <Stack gap="lg">
            <Box>
              <Title order={2}>1. INTRODUCTION</Title>
              <Text mt="md">
                This Terms of Service Agreement (the "Agreement" or "Terms") constitutes a legally binding contract between you ("you," "your," "User," or "Customer") and Progress Notes (www.progressnotes.com), a digital product of Somatopia, LLC, a California limited liability company ("Progress Notes," "we," "us," or "our").
              </Text>
              <Text mt="md">
                By accessing or using our website, mobile applications, browser extensions, and any other related services (collectively, the "Services"), you acknowledge that you have read, understood, and agree to be legally bound by these Terms and our Privacy Policy, which is incorporated by reference into these Terms.
              </Text>
              <Text mt="md">
                We encourage you to read these Terms carefully as they contain important information regarding your legal rights, remedies, and obligations, including various limitations and exclusions, and a clause that governs how disputes will be resolved. If you do not agree to these Terms, you should not access or use the Services.
              </Text>
              <Text mt="md">
                If you are accepting these Terms on behalf of a company, organization, or other legal entity, you represent and warrant that you have the authority to bind that entity to these Terms, that you have read and understand these Terms, and that you agree to these Terms on behalf of that entity.
              </Text>
              <Text mt="md">
                We may modify these Terms at any time at our sole discretion. If we make material changes to the Terms, we will provide notice through the Services, via email, or by other means to provide you the opportunity to review the changes before they become effective. Your continued use of the Services after we publish or send a notice about our changes to these Terms constitutes your consent to the updated Terms.
              </Text>
            </Box>

            <Box>
              <Title order={2}>2. SERVICES DESCRIPTION</Title>
              <Title order={3} mt="md">2.1 AI-Powered Documentation</Title>
              <Text mt="md">
                Progress Notes provides an AI-powered clinical documentation platform designed specifically for healthcare professionals, with a primary focus on mental health providers. Our Services include AI-assisted transcription of clinical sessions, automated generation of clinical documentation, organization and storage of clinical notes, analytics and insights relating to clinical documentation, and integration capabilities with electronic health record (EHR) systems. These features are designed to support healthcare professionals in efficiently documenting patient encounters while maintaining focus on patient care.
              </Text>
              
              <Title order={3} mt="lg">2.2 Disclaimer of Medical Advice</Title>
              <Text mt="md">
                The Services do not provide medical advice, diagnosis, or treatment recommendations. They are assistive tools for documentation purposes only. Any information generated by our AI systems is not a substitute for professional medical judgment. As a healthcare provider, you must review, verify, and edit all AI-generated content before finalizing clinical documentation. You understand and agree that Progress Notes is not a healthcare provider, not a medical device under applicable laws and regulations, not a substitute for professional clinical judgment, and not responsible for clinical decisions made based on the information generated by the Services. As a healthcare professional, you maintain sole responsibility for all clinical decisions, diagnoses, and treatments, and you should never rely solely on information provided by our Services for making clinical decisions.
              </Text>
            </Box>

            <Box>
              <Title order={2}>3. ACCOUNT REGISTRATION AND SECURITY</Title>
              <Title order={3} mt="md">3.1 Account Creation</Title>
              <Text mt="md">
                To access certain features of the Services, you must create an account. During registration, we ask that you provide accurate, current, and complete information. You agree to update your information as necessary to maintain its accuracy. We value your privacy and handle all registration information in accordance with our Privacy Policy.
              </Text>
              
              <Title order={3} mt="lg">3.2 Account Security</Title>
              <Text mt="md">
                You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. We recommend creating a strong password and keeping it confidential, restricting access to your account to authorized individuals, notifying us immediately of any unauthorized use of your account or any other security breach, and ensuring that you log out of your account at the end of each session when using shared devices. We reserve the right to disable your account at any time if we believe there has been a violation of these Terms or if activities occur on your account that, in our sole discretion, would or might cause damage to or impair the Services or infringe or violate any third party's rights or violate any applicable laws or regulations.
              </Text>
            </Box>

            <Box>
              <Title order={2}>4. DATA OWNERSHIP AND PRIVACY</Title>
              <Title order={3} mt="md">4.1 Ownership of Customer Data</Title>
              <Text mt="md">
                You retain all ownership rights to the data you upload, create, or generate through your use of the Services ("Customer Data"), including but not limited to patient information, session recordings, and clinical notes. Nothing in these Terms shall be construed as granting us any ownership interest in or to your Customer Data. We respect the sensitive nature of healthcare data and are committed to protecting the privacy and security of all Customer Data.
              </Text>

              <Title order={3} mt="lg">4.2 License to Customer Data</Title>
              <Text mt="md">
                By submitting Customer Data to our Services, you grant Progress Notes a non-exclusive, worldwide, royalty-free license to access, use, process, copy, distribute, perform, export, and display the Customer Data, only as reasonably necessary to provide, maintain and improve the Services; to prevent or address service, security, support, and technical issues; as required by law; and as expressly permitted in writing by you. This limited license is designed to enable us to provide you with the full functionality of our Services while respecting your ownership of the data. We will never sell or commercially exploit your Customer Data, and we will only use it as outlined in these Terms and our Privacy Policy.
              </Text>

              <Title order={3} mt="lg">4.3 De-identified Data</Title>
              <Text mt="md">
              <Text mt="md">
              You retain all ownership rights to your Customer Data. Progress Notes shall not sell, assign, or provide any Customer Data to any third party without your prior written consent. To facilitate innovation and to further develop our Services, Progress Notes reserves the right to compile, collect, and use data generated from your use of the Services in de-identified, anonymous, and aggregate form for analytical and other business purposes (collectively, the "De-Identified Data"). Such De-Identified Data is created in accordance with HIPAA and other applicable regulations. De-Identified Data is not Customer Data. Progress Notes shall own all right, title, and interest in and to the De-Identified Data and may use it for purposes permitted under applicable law, such as improving our Services and developing new features.
              </Text>              </Text>

              <Title order={3} mt="lg">4.4 HIPAA Compliance</Title>
              <Text mt="md">
                If you are a Covered Entity or Business Associate under HIPAA, and you provide Protected Health Information (PHI) to Progress Notes, you agree to enter into our Business Associate Agreement (BAA), which is incorporated by reference into these Terms. Our BAA describes our respective obligations for the protection, use, and disclosure of PHI. Progress Notes implements technical, administrative, and physical safeguards designed to protect the confidentiality, integrity, and availability of PHI as required by HIPAA. However, you remain responsible for your own compliance with HIPAA and other applicable laws and regulations. We take our obligations under HIPAA seriously and are committed to supporting your compliance efforts.
              </Text>

              <Title order={3} mt="lg">4.5 Data Storage and Retention</Title>
              <Text mt="md">
                Session recordings are processed by our systems and, by default, are deleted after processing unless you specifically request otherwise. This approach minimizes the retention of sensitive audio data while still allowing you to benefit from our transcription and documentation services. Generated clinical notes and documentation will be retained in accordance with our data retention policies as described in our Privacy Policy. We recommend that you export or back up any Customer Data that you wish to retain beyond our retention periods to your own secure storage systems.
              </Text>
            </Box>

            <Box>
              <Title order={2}>5. USER OBLIGATIONS AND RESTRICTIONS</Title>
              <Title order={3} mt="md">5.1 Consent Requirements</Title>
              <Text mt="md">
                As a healthcare professional, you are solely responsible for obtaining all necessary consents, authorizations, and permissions from patients or clients before recording sessions or uploading their information to the Services. Such consent must comply with all applicable laws, regulations, and professional standards, including but not limited to HIPAA, state privacy laws, and professional ethical guidelines. You represent and warrant that you have obtained valid consent from all patients or clients whose information is submitted to or processed through the Services. We provide tools and resources to help you manage consent processes, but ultimately the responsibility for obtaining proper consent rests with you as the healthcare provider.
              </Text>

              <Title order={3} mt="lg">5.2 Prohibited Uses</Title>
              <Text mt="md">
                The Services are designed to support legitimate healthcare documentation needs. You agree not to use the Services to violate any applicable law, regulation, or professional standard; infringe the intellectual property rights or violate the privacy rights of any third party; upload, transmit, or distribute any content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, invasive of another's privacy, or otherwise objectionable; upload or transmit any material containing software viruses, worms, Trojan horses, or other harmful computer code; interfere with or disrupt the integrity or performance of the Services; attempt to gain unauthorized access to the Services or related systems or networks; use the Services for any purpose other than as expressly permitted by these Terms; or engage in any high-risk use of the Services, including use in connection with emergency services, critical health monitoring, or any application where failure could lead to death, personal injury, or environmental damage.
              </Text>

              <Title order={3} mt="lg">5.3 Professional Responsibility</Title>
              <Text mt="md">
                As a healthcare professional, you acknowledge and agree that you remain solely responsible for the provision of healthcare services to your patients. The Services are designed to assist with documentation, but they do not replace your professional judgment. You should critically review all AI-generated content before using it in clinical documentation, exercise independent professional judgment when using information generated by the Services, and not rely on the Services as a substitute for your professional expertise or judgment. Additionally, you agree to use the Services in compliance with all applicable professional standards and ethical guidelines that govern your practice.
              </Text>
            </Box>

            <Box>
              <Title order={2}>6. INTELLECTUAL PROPERTY RIGHTS</Title>
              <Title order={3} mt="md">6.1 Progress Notes' Intellectual Property</Title>
              <Text mt="md">
                All rights, title, and interest in and to the Services, including all intellectual property rights in the software, algorithms, machine learning models, user interface designs, and other elements of the Services, are owned by Progress Notes or its licensors. The Services are protected by copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws. We have invested significant resources in developing our technology, and we are committed to protecting our intellectual property rights while providing you with a valuable service.
              </Text>

              <Title order={3} mt="lg">6.2 Limited License to Services</Title>
              <Text mt="md">
                Subject to your compliance with these Terms, Progress Notes grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the Services for your internal professional purposes only. This license does not include any resale or commercial use of the Services or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of the Services or its contents; or any use of data mining, robots, or similar data gathering and extraction tools. The license granted under these Terms is solely for the purpose of enabling you to use the Services as provided by Progress Notes, and in the manner permitted by these Terms.
              </Text>

              <Title order={3} mt="lg">6.3 Restrictions on Use</Title>
              <Text mt="md">
                To maintain the integrity of our Services and protect our intellectual property, you may not copy, modify, or create derivative works based on the Services; reverse engineer, decompile, disassemble, or otherwise attempt to discover the source code, object code, or underlying structure, ideas, or algorithms of the Services; rent, lease, lend, sell, license, sublicense, assign, distribute, publish, transfer, or otherwise make available the Services to any third party; remove or alter any copyright, trademark, or other proprietary notices from the Services; use the Services to build a competitive product or service; or use the Services in any manner that exceeds the scope of the license granted herein. These restrictions help ensure that we can continue to provide high-quality services to all of our users.
              </Text>

              <Title order={3} mt="lg">6.4 Feedback and Improvements</Title>
              <Text mt="md">
                We value your input and are always looking for ways to improve our Services. If you provide any ideas, suggestions, recommendations, feedback, or improvements related to the Services ("Feedback"), you hereby assign to Progress Notes all right, title, and interest in and to such Feedback. Progress Notes shall have the right to use, implement, disclose, distribute, modify, and otherwise exploit such Feedback for any purpose without compensation or attribution to you. You acknowledge that any developments, improvements, or new features that you request or suggest, even if developed in collaboration with Progress Notes, shall be the property of Progress Notes. This enables us to continuously improve our platform for the benefit of all users. We appreciate your contributions to making our Services better and will always strive to use your feedback to enhance the user experience.
              </Text>
            </Box>

            <Box>
              <Title order={2}>7. PRICING AND PAYMENT</Title>
              <Title order={3} mt="md">7.1 Subscription Plans</Title>
              <Text mt="md">
                Progress Notes offers various subscription plans with different features and pricing tiers to accommodate the needs of different healthcare practices. Current pricing information is available on our website. We reserve the right to change our pricing at any time, but we will always provide notice of any changes before they become effective to allow you to make informed decisions about your subscription. Subscription fees are billed in advance and are non-refundable except as explicitly provided in these Terms. If you upgrade to a higher-tier plan, the upgrade will take effect immediately, and you will be charged a prorated amount for the remainder of your current billing cycle to ensure a seamless transition.
              </Text>

              <Title order={3} mt="lg">7.2 Payment Processing</Title>
              <Text mt="md">
                We strive to make payment as convenient as possible. You agree to provide accurate and complete billing information, including valid payment method information. By providing your payment information, you authorize us or our third-party payment processors to charge your payment method for all fees incurred. All payments are processed in US Dollars. If your payment cannot be completed, we may need to suspend or terminate your access to the Services until payment issues are resolved. We will always attempt to notify you of any payment issues before taking action on your account.
              </Text>

              <Title order={3} mt="lg">7.3 Subscription Renewal</Title>
              <Text mt="md">
                For your convenience, all subscriptions automatically renew for additional periods equal to the initial subscription term unless you cancel your subscription before the renewal date. This ensures uninterrupted access to the Services for your practice. You may cancel your subscription at any time through your account settings or by contacting our customer support team. We're always here to help with any questions or concerns about your subscription.
              </Text>

              <Title order={3} mt="lg">7.4 Refund Policy</Title>
              <Text mt="md">
                We want you to be satisfied with our Services. We offer a limited refund policy as follows: If you cancel your subscription within 7 days of your initial subscription purchase and have not used the Services beyond basic account setup, you may request a full refund. Additionally, if we experience a prolonged service outage (more than 24 consecutive hours) that materially impacts your ability to use the Services, you may request a prorated refund for the affected period. No refunds will be provided for partial subscription periods or for cancellations after the 7-day period has elapsed. To request a refund, please contact our customer support team with your account information and reason for the refund request. We will review all refund requests promptly and fairly.
              </Text>

              <Title order={3} mt="lg">7.5 Taxes</Title>
              <Text mt="md">
                All fees are exclusive of taxes. You are responsible for paying all taxes associated with your purchase of the Services, including but not limited to sales tax, value-added tax, and goods and services tax. If Progress Notes is legally obligated to collect taxes on the sale of the Services, we will add the applicable tax to your billing statement. We strive to be transparent about all costs associated with our Services.
              </Text>
            </Box>

            <Box>
              <Title order={2}>8. LIMITATION OF LIABILITY</Title>
              <Title order={3} mt="md">8.1 Disclaimer of Warranties</Title>
              <Text mt="md">
                The Services are provided "as is" and "as available," without warranty of any kind, either express or implied. To the maximum extent permitted by applicable law, Progress Notes expressly disclaims all warranties, whether express, implied, statutory or otherwise, including but not limited to the implied warranties of merchantability, fitness for a particular purpose, non-infringement, and any warranties arising out of course of dealing or usage of trade. Progress Notes makes no warranty that the Services will meet your requirements or expectations; the Services will be uninterrupted, timely, secure, or error-free; the results that may be obtained from the use of the Services will be accurate or reliable; or any errors in the Services will be corrected. The AI-generated content provided through the Services may contain inaccuracies or errors. You acknowledge that you are solely responsible for reviewing, verifying, and approving all AI-generated content before using it in clinical documentation. While we strive to provide high-quality services, the nature of AI technology and healthcare documentation requires professional review and judgment.
              </Text>

              <Title order={3} mt="lg">8.2 Limitation of Liability</Title>
              <Text mt="md">
                To the maximum extent permitted by applicable law, in no event shall Progress Notes, its affiliates, officers, directors, employees, agents, suppliers or licensors be liable for any indirect, punitive, incidental, special, consequential, or exemplary damages, including without limitation damages for loss of profits, goodwill, use, data or other intangible losses, that result from the use of, or inability to use, the Services. Under no circumstances will Progress Notes be responsible for any damage, loss, or injury resulting from hacking, tampering, or other unauthorized access or use of the Services or your account or the information contained therein. To the maximum extent permitted by applicable law, the maximum liability of Progress Notes arising out of or in connection with the Services or these Terms, whether in contract, tort (including negligence), strict liability, or otherwise, shall not exceed the amount you have paid to Progress Notes in the twelve (12) months immediately preceding the event giving rise to the claim.
              </Text>

              <Title order={3} mt="lg">8.3 Allocation of Risk</Title>
              <Text mt="md">
                You acknowledge and agree that the foregoing disclaimers and limitations of liability represent a reasonable allocation of risk and that Progress Notes would not make the Services available without such disclaimers and limitations. You further acknowledge that the fees charged by Progress Notes reflect this allocation of risk and the limitation of liability specified herein. These provisions are essential to our ability to offer the Services at current pricing levels.
              </Text>
            </Box>

            <Box>
              <Title order={2}>9. INDEMNIFICATION</Title>
              <Text mt="md">
                We value the trusted relationship we have with our users, and we expect all users to comply with applicable laws and these Terms. You agree to defend, indemnify, and hold harmless Progress Notes, its affiliates, subsidiaries, and each of their officers, directors, employees, agents, partners, and representatives from and against any and all claims, demands, actions, liabilities, costs, or damages, including reasonable attorneys' fees, arising out of or relating to your access to or use of the Services; your Customer Data; your violation of these Terms; your violation of any applicable law, regulation, or professional standard; your infringement or violation of any third-party right, including without limitation any intellectual property right or privacy right; any claim that your use of the Services has harmed a third party; or any disputes between you and any third party, including patients or clients. This indemnification obligation will survive the termination or expiration of these Terms and your use of the Services. If we receive a claim that may be subject to indemnification, we will attempt to notify you promptly and work with you to resolve the matter.
              </Text>
            </Box>

            <Box>
              <Title order={2}>10. TERM AND TERMINATION</Title>
              <Title order={3} mt="md">10.1 Term</Title>
              <Text mt="md">
                These Terms will remain in full force and effect while you use the Services or maintain an account with us, unless terminated earlier as provided in these Terms. We value long-term relationships with our users and strive to provide consistent, reliable service throughout the term of our agreement.
              </Text>

              <Title order={3} mt="lg">10.2 Termination by You</Title>
              <Text mt="md">
                You may terminate these Terms at any time by canceling your account and ceasing all use of the Services. If you cancel your account, you may continue to use the Services until the end of your current billing cycle, but you will not receive a refund for any fees already paid unless otherwise specified in our refund policy. We make the cancellation process straightforward and transparent, and our support team is available to assist with any questions during this process.
              </Text>

              <Title order={3} mt="lg">10.3 Termination by Progress Notes</Title>
              <Text mt="md">
                Progress Notes may terminate or suspend your access to the Services or your account with notice for any material breach of these Terms, failure to pay any fees when due, upon request by law enforcement or other government agencies, due to unexpected technical issues or service discontinuation, or if we believe your actions may cause legal liability for you, our users, or Progress Notes. In most cases, we will provide notice and an opportunity to remedy any issues before termination. We view termination as a last resort and will work with you to resolve any concerns whenever possible.
              </Text>

              <Title order={3} mt="lg">10.4 Effect of Termination</Title>
              <Text mt="md">
                Upon termination of these Terms for any reason, your license to use the Services will end, your right to access your account and the Services will cease, all fees accrued before termination will become immediately due and payable, and Progress Notes may, but is not obligated to, delete your Customer Data in accordance with our data retention policies. We recommend exporting any important data before terminating your account to ensure you retain access to your information.
              </Text>

              <Title order={3} mt="lg">10.5 Survival</Title>
              <Text mt="md">
                Certain provisions of these Terms, due to their nature, will survive termination, including but not limited to provisions regarding Data Ownership and Privacy, Intellectual Property Rights, Limitation of Liability, Indemnification, Effect of Termination, Dispute Resolution, and General Provisions. These surviving terms ensure that both parties' rights and obligations regarding past use of the Services are preserved even after the relationship ends.
              </Text>
            </Box>

            <Box>
              <Title order={2}>11. DISPUTE RESOLUTION</Title>
              <Title order={3} mt="md">11.1 Binding Arbitration</Title>
              <Text mt="md">
                We hope to address any concerns you may have about our Services directly, but in the event of an unresolved dispute, the following provisions will apply. Please read this section carefully as it affects your legal rights, including your right to file a lawsuit in court. You and Progress Notes agree that any dispute, claim, or controversy arising out of or relating to these Terms or the Services will be settled by binding arbitration, except that each party retains the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation, or violation of a party's copyrights, trademarks, trade secrets, patents, or other intellectual property rights. You acknowledge and agree that you and Progress Notes are each waiving the right to a trial by jury and the right to participate as a plaintiff or class member in any purported class action, representative, or private attorney general proceeding. We believe that arbitration provides a fair, efficient, and less adversarial method of resolving disputes.
              </Text>

              <Title order={3} mt="lg">11.2 Arbitration Rules</Title>
              <Text mt="md">
                The arbitration will be administered by the American Arbitration Association ("AAA") in accordance with the Commercial Arbitration Rules and the Supplementary Procedures for Consumer Related Disputes (the "AAA Rules") then in effect, except as modified by this section. The Federal Arbitration Act will govern the interpretation and enforcement of this section. The AAA Rules provide a fair and established framework for resolving disputes.
              </Text>

              <Title order={3} mt="lg">11.3 Arbitration Process</Title>
              <Text mt="md">
                A party who desires to initiate arbitration must provide the other party with a written Demand for Arbitration as specified in the AAA Rules. The arbitrator will be either a retired judge or an attorney licensed to practice law in the state of California and will be selected by the parties from the AAA's roster of consumer dispute arbitrators. This ensures that the arbitrator will have the appropriate legal background to understand the issues involved in the dispute.
              </Text>

              <Title order={3} mt="lg">11.4 Arbitration Location and Procedure</Title>
              <Text mt="md">
                Unless you and Progress Notes otherwise agree, the arbitration will be conducted in California. If your claim does not exceed $10,000, then the arbitration will be conducted solely on the basis of documents you and Progress Notes submit to the arbitrator, unless you request a hearing or the arbitrator determines that a hearing is necessary. This approach is designed to make the arbitration process as convenient and cost-effective as possible.
              </Text>

              <Title order={3} mt="lg">11.5 Arbitrator's Decision</Title>
              <Text mt="md">
                The arbitrator will render an award within the timeframe specified in the AAA Rules. The arbitrator's decision will include the essential findings and conclusions upon which the arbitrator based the award. Judgment on the arbitration award may be entered in any court having jurisdiction thereof. The arbitrator is bound to follow applicable law and render a reasoned decision.
              </Text>

              <Title order={3} mt="lg">11.6 Class Action Waiver</Title>
              <Text mt="md">
                You and Progress Notes agree that each may bring claims against the other only in your or its individual capacity and not as a plaintiff or class member in any purported class or representative proceeding. Further, unless both you and Progress Notes agree otherwise, the arbitrator may not consolidate more than one person's claims and may not otherwise preside over any form of a representative or class proceeding. This provision ensures that disputes are addressed on an individual basis.
              </Text>

              <Title order={3} mt="lg">11.7 Severability</Title>
              <Text mt="md">
                If any part of this dispute resolution section is found to be illegal or unenforceable, the remainder will remain in effect, except that if a finding of partial illegality or unenforceability would allow class or representative arbitration, this section will be unenforceable in its entirety. We have structured this section to be enforceable under current law while protecting the rights of both parties.
              </Text>

              <Title order={3} mt="lg">11.8 Option to Opt-Out</Title>
              <Text mt="md">
                You have the right to opt-out and not be bound by the arbitration and class action waiver provisions by sending written notice of your decision to opt-out to our address or email within 30 days of your first use of the Services. If you do not opt out within this period, you will be bound by these provisions. This opt-out option ensures that you have a meaningful choice regarding how potential disputes will be resolved.
              </Text>
            </Box>

            <Box>
              <Title order={2}>12. GENERAL PROVISIONS</Title>
              <Title order={3} mt="md">12.1 Governing Law</Title>
              <Text mt="md">
                These Terms and any action related thereto will be governed by the laws of the State of California without regard to its conflict of laws provisions. The exclusive jurisdiction and venue of any action with respect to the subject matter of these Terms will be the state and federal courts located in California, and each of the parties hereto waives any objection to jurisdiction and venue in such courts. This provision establishes a clear legal framework for interpreting and enforcing these Terms.
              </Text>

              <Title order={3} mt="lg">12.2 Geographic Restrictions</Title>
              <Text mt="md">
                The Services are primarily intended for use by persons located in the United States. If you access the Services from outside the United States, you do so on your own initiative and are responsible for compliance with local laws. You may not use the Services if you are a resident of, or are located in, a country that is subject to a U.S. government embargo or sanctions, or that has been designated by the U.S. government as a "terrorist supporting" country, or if you are listed on any U.S. government list of prohibited or restricted parties. You represent and warrant that you are not located in, under the control of, or a national or resident of any such country. These restrictions are necessary to ensure compliance with U.S. trade laws and regulations.
              </Text>

              <Title order={3} mt="lg">12.3 Entire Agreement</Title>
              <Text mt="md">
                These Terms constitute the entire agreement between you and Progress Notes regarding the Services and supersede all prior and contemporaneous agreements, proposals, or representations, written or oral, concerning their subject matter. We have included all material terms in this document to provide clarity and avoid misunderstandings about the rights and obligations of each party.
              </Text>

              <Title order={3} mt="lg">12.4 Waiver and Severability</Title>
              <Text mt="md">
                No waiver by Progress Notes of any term or condition set out in these Terms shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of Progress Notes to assert a right or provision under these Terms shall not constitute a waiver of such right or provision. If any provision of these Terms is held by a court or other tribunal of competent jurisdiction to be invalid, illegal, or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of the Terms will continue in full force and effect. This ensures that these Terms remain enforceable even if individual provisions are challenged.
              </Text>

              <Title order={3} mt="lg">12.5 Assignment</Title>
              <Text mt="md">
                You may not assign or transfer these Terms, by operation of law or otherwise, without Progress Notes' prior written consent. Any attempt by you to assign or transfer these Terms without such consent will be null and void. Progress Notes may freely assign or transfer these Terms without restriction, provided that we will notify you of any such assignment or transfer. This provision ensures that we maintain a direct relationship with each user while preserving our ability to restructure our business if necessary.
              </Text>

              <Title order={3} mt="lg">12.6 Notices</Title>
              <Text mt="md">
                Except as otherwise stated in these Terms, any notice to Progress Notes should be sent by mail to the following address:
              </Text>
              <Text mt="md">
                Progress Notes<br />
                A digital product of Somatopia, LLC<br />
                1 H St #203<br />
                San Rafael, CA 94901
              </Text>
              <Text mt="md">
                We may provide you with notices, including those regarding changes to these Terms, by email, regular mail, or postings on the Services. This ensures that both parties have reliable methods for communicating important information about these Terms and the Services.
              </Text>

              <Title order={3} mt="lg">12.7 Force Majeure</Title>
              <Text mt="md">
                Progress Notes shall not be liable for any delay or failure to perform resulting from causes outside its reasonable control, including, but not limited to, acts of God, natural disasters, war, terrorism, riots, civil unrest, embargoes, acts of civil or military authorities, fire, floods, accidents, strikes or shortages of transportation facilities, fuel, energy, labor or materials. This provision recognizes that certain events beyond our control may temporarily affect our ability to provide the Services.
              </Text>

              <Title order={3} mt="lg">12.8 No Third-Party Beneficiaries</Title>
              <Text mt="md">
                These Terms do not and are not intended to confer any rights or remedies upon any person other than you and Progress Notes. This clarifies that only the direct parties to these Terms may enforce their provisions.
              </Text>

              <Title order={3} mt="lg">12.9 Contact Information</Title>
              <Text mt="md">
                If you have any questions about these Terms or our Services, please contact us at:
              </Text>
              <Text mt="md">
                Email: support@progressnotes.com<br />
                Phone: (415) 545-8899<br />
                Address: 1 H St #203, San Rafael, CA 94901
              </Text>
              <Text mt="md">
                We welcome your feedback and are committed to addressing any questions or concerns about our Terms or Services.
              </Text>
            </Box>

            <Box>
              <Title order={2}>13. ACKNOWLEDGMENT</Title>
              <Text mt="md">
                By using the Services, you acknowledge that you have read these Terms, understand them, and agree to be bound by them. We appreciate your trust in Progress Notes and look forward to supporting your clinical documentation needs.
              </Text>
            </Box>

            <Box ta="center">
              <Text size="lg">Effective Date: {currentDate}</Text>
            </Box>
          </Stack>
        </Stack>
      </Paper>
    </Container>
  );
};

export default TermsOfService;