export const MEDPLUM_GOOGLE_CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID;
export const MEDPLUM_RECAPTCHA_SITE_KEY = import.meta.env.VITE_RECAPTCHA_SITE_KEY;
export const MEDPLUM_PROJECT_ID = import.meta.env.VITE_MEDPLUM_PROJECT_ID;
//export const MEDPLUM_PROJECT_ID = '019521df-2696-707b-84df-205d80537b3c';
export const STRIPE_PUBLIC_KEY = import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY;
